version: '3.8'
services:
  sumo_data_collector:
    image: ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sumo_dockerized
    ports:
      - "1337:1337"
    volumes:
      - ./simulations:/simulations
      - ./results:/results
    command: /entrypoint.sh
