name: SUMO Dockerized

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v2

      - name: install compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build and push image to ghcr
        run: |
          docker-compose -f docker-compose.yml build
          docker tag tp2024-25_sumo_dockerized ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized:latest
          docker push ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized:latest

      - name: verify
        run: docker images ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized:latest
