name: SUMO Dockerized

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v2

      - name: login to repo
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: install compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build and push ghcr
        env:
          COMPOSE_HTTP_TIMEOUT: 99999
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: verify
        run: |
          docker images ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized:latest
          docker images ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized_analyzer:latest
