name: SUMO Dockerized

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push SUMO Image
        env:
          COMPOSE_HTTP_TIMEOUT: 99999
        run: |
          docker build -t ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized:latest -f Dockerfile .
          docker push ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized:latest

      - name: Build and Push Analyzer Image
        run: |
          docker build -t ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized_analyzer:latest -f Dockerfile.datacollect .
          docker push ghcr.io/dominikmifkovic/tp2024-25_sumo_dockerized_analyzer:latest
